modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="aster_risk"
version="1.0.1"
displayName="Aster Risk"
displayURL="https://mcreator.net,"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator,starMaylight"
description="moonlight,ritual,andmore! ,issue:https://github.com/starMaylight/aster_risk/issues"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.aster_risk]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration